version: "3.9"
services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: rezonit
      POSTGRES_USER: rezonit
      POSTGRES_PASSWORD: '1234'
      PGDATA: /var/lib/postgresql/pgdata
    networks:
      - internal
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - /var/lib/postgresql/pgdata:/var/lib/postgresql/pgdata

  rezonit:
    build: .
    image: rezonit
    depends_on:
      - postgresql
    environment:
      DSN: postgres://rezonit:1234@postgresql:5432/rezonit?sslmode=disable
    networks:
      - internal
    ports:
      - "3000:3000"

networks:
  internal:
    name: internal